version: '3'
services:
  web:
    image: muchat-react
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/docker-entrypoint.sh:/app/docker/docker-entrypoint.sh
    ports:
     - "3000:80"
    environment:
      REACT_APP_HOSTNAME: localhost